# Generated by Django 2.2.7 on 2020-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycomuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='error',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failed', 'failed')], default='processing', max_length=55),
        ),
    ]
