# Generated by Django 3.1.7 on 2021-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycomuz', '0002_auto_20200111_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancel_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='perform_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], default='processing', max_length=55),
        ),
    ]
