# Generated by Django 3.1.7 on 2021-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycomuz', '0003_auto_20210303_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cancel_datetime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_datetime',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perform_datetime',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
